name: Deploy

on:
  workflow_run:
    workflows:
      - Publish Docker Images
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::227246780882:role/docker-task-manager-github-deploy
          aws-region: ap-south-1

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
          --targets "Key=tag:Deployment,Values=docker-task-manager" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd ~/docker-task-manager",
              "IMAGE_TAG=${{ github.event.workflow_run.head_sha }} docker compose -f compose.production.yml pull",
              "IMAGE_TAG=${{ github.event.workflow_run.head_sha }} docker compose -f compose.production.yml up -d"
            ]' \
            --comment "Deploy ${{ github.event.workflow_run.head_sha }}"