name: Publish Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry #Login into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image owner
        run: echo "IMAGE_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"

      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ghcr.io/${{ env.IMAGE_OWNER }}/docker-task-manager-server:latest

      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ghcr.io/${{ env.IMAGE_OWNER }}/docker-task-manager-client:latest